[build-system]
requires = [
    "setuptools>=61.0",
    "pip>=22.3"
]
build-backend = "setuptools.build_meta"

[project]
name = "tiktok_web_signer"
version = "0.1.0"
description = "Sign API requests"
readme = "README.md"
requires-python = ">=3.8"




[tool.setuptools.packages.find]
include = ["tiktok_web_signer*"]